
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Siddharth
 */
public class ExonDisplayPanel extends javax.swing.JPanel {
    int state=0;
    int gene_start;
    int gene_end;
    ArrayList<Integer> exon_starts= new ArrayList<>();
    ArrayList<Integer> exon_ends = new ArrayList<>();
    ArrayList<Double> exon_start_convert = new ArrayList<>();
    ArrayList<Double> exon_end_convert = new ArrayList<>();
    String gene_name="";
    
    /**
     * Creates new form ExonDisplayPanel
     */
    public ExonDisplayPanel() {
        initComponents();
    }
    
    public void convert_exon_positions(){
    double gene_length=gene_end-gene_start;
    for(int i=0;i<exon_starts.size();i++){
        double start=(exon_starts.get(i)-gene_start)/gene_length;
        double end =(exon_ends.get(i)-gene_start)/gene_length;
        exon_start_convert.add(start);
        exon_end_convert.add(end);
    }
        System.out.println(exon_start_convert.toString());
        System.out.println(exon_end_convert.toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g){
        if(state==0){
        super.paintComponent(g);}
        else{
    super.paintComponent(g);
    convert_exon_positions();
    g.drawRect(30, 200, 1000, 50);
    g.setFont(new Font("Times Roman",Font.PLAIN,20));
    g.drawString(gene_name, 30,100);
    g.setFont(new Font("Times Roman",Font.PLAIN,10));
    g.setColor(Color.red);
    for(int i=0;i<exon_start_convert.size();i++){
        int start=(int) (30 + exon_start_convert.get(i)*1000);
        int end= (int) (30 + exon_end_convert.get(i)*1000);
        //System.out.println(Integer.toString(start) +  " " + Integer.toString(end));
        g.fillRect(start,200, end-start, 50);
        g.setColor(Color.BLACK);
        if(!exon_starts.get(i).equals(gene_start)){
            g.drawString(Integer.toString(gene_start), 30, 270);
        }
        if(!exon_ends.get(i).equals(gene_end)){
            g.drawString(Integer.toString(gene_end),1030,270);
        }
        g.drawString(exon_starts.get(i).toString(), start, 270);
        g.drawString(exon_ends.get(i).toString(),end,270);
        g.setColor(Color.red);
    }
    exon_start_convert.clear();
    exon_end_convert.clear();
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
